apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: clo835
  region: "us-east-1"
  version: "1.31"



vpc:
  id: vpc-05a06dca6483e4309  # Specify your existing VPC ID here
  subnets:
    private:
      us-east-1a:
        cidr: "172.31.32.0/20"  # Private subnet in AZ us-east-1a
      us-east-1b:
        cidr: "172.31.0.0/20"  # Private subnet in AZ us-east-1b
    public:
      us-east-1c:
        cidr: "172.31.80.0/20"  # Public subnet in AZ us-east-1a
      us-east-1d:
        cidr: "172.31.16.0/20"  # Public subnet in AZ us-east-1b

iam:
  serviceRoleARN: arn:aws:iam::117426110282:role/LabRole
  

managedNodeGroups:
  - name: nodegroup
    desiredCapacity: 2
    instanceType: t3.small
    ssh:
      enableSsm: true
    iam:
      instanceRoleARN: arn:aws:iam::117426110282:role/LabRole
      
