apiVersion: v1
kind: Service
metadata:
  name: flask-service
  namespace: final
spec:
  selector:
    app: flask
  ports:
    - protocol: TCP
      port: 80
      targetPort: 81  # Mapping internal container port 81 to external port 80
  type: LoadBalancer  # Exposing via LoadBalancer for external access

