apiVersion: v1
kind: Service
metadata:
  name: mysql-db
  namespace: final
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306  # Expose MySQL's default port
      targetPort: 3306
  clusterIP: None  # Headless service, enables direct access from other pods

